name: composer-env
channels:
  - conda-forge
dependencies:
  - python=3.11
  - numpy
  - pandas
  - matplotlib
  - seaborn
  - scikit-learn=1.3.2
  - imbalanced-learn=0.11.0 
  - pretty_midi
  - pygame
  - tensorflow